//
//  XiTongfaceCode.m
//  Yiban
//
//  Created by tom zeng on 13-1-31.
//
//

#import "XiTongFaceCode.h"

@implementation XiTongFaceCode
-(NSMutableDictionary*)XiTongToServer{

    NSMutableDictionary *dict = [[[NSMutableDictionary alloc]init]autorelease];
     [dict setValue:@"\xf0\x9f\x98\x84"forKey:@"[笑]"];
      [dict setValue:@"\xe2\x98\x80"forKey:@"[日与光线]"];
      [dict setValue:@"\xe2\x98\x81"forKey:@"[云]"];
      [dict setValue:@"\xe2\x98\x94"forKey:@"[伞，雨滴]"];
      [dict setValue:@"\xe2\x9b\x84"forKey:@"[雪人无雪]"];
      [dict setValue:@"\xe2\x9a\xa1"forKey:@"[高电压]"];
      [dict setValue:@"\xf0\x9f\x8c\x80"forKey:@"[气旋]"];
      [dict setValue:@"\xf0\x9f\x8c\x81"forKey:@"[云里雾里]"];
      [dict setValue:@"\xf0\x9f\x8c\x82"forKey:@"[合起来的伞]"];
      [dict setValue:@"\xf0\x9f\x8c\x83"forKey:@"[星空]"];
      [dict setValue:@"\xf0\x9f\x8c\x84"forKey:@"[日出山]"];
      [dict setValue:@"\xf0\x9f\x8c\x85"forKey:@"[太阳升起]"];
      [dict setValue:@"\xf0\x9f\x8c\x86"forKey:@"[黄昏时分]"];
      [dict setValue:@"\xf0\x9f\x8c\x87"forKey:@"[日落时的建筑]"];
      [dict setValue:@"\xf0\x9f\x8c\x88"forKey:@"[彩虹]"];
      [dict setValue:@"\xe2\x9d\x84"forKey:@"[雪花]"];
      [dict setValue:@"\xe2\x9b\x85"forKey:@"[云]"];
      [dict setValue:@"\xf0\x9f\x8c\x89"forKey:@"[夜泊]"];
      [dict setValue:@"\xf0\x9f\x8c\x8a"forKey:@"[水波]"];
      [dict setValue:@"\xf0\x9f\x8c\x8b"forKey:@"[火山]"];
      [dict setValue:@"\xf0\x9f\x8c\x8c"forKey:@"[乳白色的]"];
      [dict setValue:@"\xf0\x9f\x8c\x8f"forKey:@"[地球]"];
      [dict setValue:@"\xf0\x9f\x8c\x91"forKey:@"[新月]"];
      [dict setValue:@"\xf0\x9f\x8c\x94"forKey:@"[残月]"];
      [dict setValue:@"\xf0\x9f\x8c\x93"forKey:@"[上弦月]"];
      [dict setValue:@"\xf0\x9f\x8c\x99"forKey:@"[镰刀型的月亮]"];
      [dict setValue:@"\xf0\x9f\x8c\x95"forKey:@"[满月]"];
      [dict setValue:@"\xf0\x9f\x8c\x9b"forKey:@"[上弦月]"];
      [dict setValue:@"\xf0\x9f\x8c\x9f"forKey:@"[星星]"];
      [dict setValue:@"\xf0\x9f\x8c\xa0"forKey:@"[流星]"];
      [dict setValue:@"\xf0\x9f\x95\x90"forKey:@"[1点]"];
      [dict setValue:@"\xf0\x9f\x95\x91"forKey:@"[2点]"];
      [dict setValue:@"\xf0\x9f\x95\x92"forKey:@"[3点]"];
      [dict setValue:@"\xf0\x9f\x95\x93"forKey:@"[四点]"];
      [dict setValue:@"\xf0\x9f\x95\x94"forKey:@"[五点钟]"];
      [dict setValue:@"\xf0\x9f\x95\x95"forKey:@"[六点钟]"];
      [dict setValue:@"\xf0\x9f\x95\x96"forKey:@"[7点]"];
      [dict setValue:@"\xf0\x9f\x95\x97"forKey:@"[晚八时]"];
      [dict setValue:@"\xf0\x9f\x95\x98"forKey:@"[九点钟]"];
      [dict setValue:@"\xf0\x9f\x95\x99"forKey:@"[十点钟]"];
      [dict setValue:@"\xf0\x9f\x95\x9a"forKey:@"[11点钟]"];
      [dict setValue:@"\xf0\x9f\x95\x9b"forKey:@"[12点钟]"];
      [dict setValue:@"\xe2\x8c\x9a"forKey:@"[手表]"];
      [dict setValue:@"\xe2\x8c\x9b"forKey:@"[沙漏]"];
      [dict setValue:@"\xe2\x8f\xb0"forKey:@"[闹钟]"];
      [dict setValue:@"\xe2\x8f\xb3"forKey:@"[流沙]"];
      [dict setValue:@"\xe2\x99\x88"forKey:@"[白羊座]"];
      [dict setValue:@"\xe2\x99\x89"forKey:@"[金牛座]"];
      [dict setValue:@"\xe2\x99\x8a"forKey:@"[双子座]"];
      [dict setValue:@"\xe2\x99\x8b"forKey:@"[癌症]"];
      [dict setValue:@"\xe2\x99\x8c"forKey:@"[狮子座]"];
      [dict setValue:@"\xe2\x99\x8d"forKey:@"[处女座]"];
      [dict setValue:@"\xe2\x99\x8e"forKey:@"[天秤座]"];
      [dict setValue:@"\xe2\x99\x8f"forKey:@"[天蝎座]"];
      [dict setValue:@"\xe2\x99\x90"forKey:@"[射手座]"];
      [dict setValue:@"\xe2\x99\x91"forKey:@"[摩羯座]"];
      [dict setValue:@"\xe2\x99\x92"forKey:@"[水瓶座]"];
      [dict setValue:@"\xe2\x99\x93"forKey:@"[双鱼座]"];
      [dict setValue:@"\xe2\x9b\x8e"forKey:@"[蛇夫座]"];
      [dict setValue:@"\xf0\x9f\x8d\x80"forKey:@"[三叶草]"];
      [dict setValue:@"\xf0\x9f\x8c\xb7"forKey:@"[郁金香]"];
      [dict setValue:@"\xf0\x9f\x8c\xb1"forKey:@"[幼苗]"];
      [dict setValue:@"\xf0\x9f\x8d\x81"forKey:@"[枫叶]"];
      [dict setValue:@"\xf0\x9f\x8c\xb8"forKey:@"[樱花]"];
      [dict setValue:@"\xf0\x9f\x8c\xb9"forKey:@"[玫瑰]"];
      [dict setValue:@"\xf0\x9f\x8d\x82"forKey:@"[落叶]"];
      [dict setValue:@"\xf0\x9f\x8d\x83"forKey:@"[飘叶]"];
      [dict setValue:@"\xf0\x9f\x8c\xba"forKey:@"[木槿花]"];
      [dict setValue:@"\xf0\x9f\x8c\xbb"forKey:@"[向日葵]"];
      [dict setValue:@"\xf0\x9f\x8c\xb4"forKey:@"[棕榈树]"];
      [dict setValue:@"\xf0\x9f\x8c\xb5"forKey:@"[仙人掌]"];
      [dict setValue:@"\xf0\x9f\x8c\xbe"forKey:@"[的稻穗]"];
      [dict setValue:@"\xf0\x9f\x8c\xbD"forKey:@"[耳玉米]"];
      [dict setValue:@"\xf0\x9f\x8d\x84"forKey:@"[蘑菇]"];
      [dict setValue:@"\xf0\x9f\x8c\xb0"forKey:@"[板栗]"];
      [dict setValue:@"\xf0\x9f\x8c\xbC"forKey:@"[盛开的花]"];
      [dict setValue:@"\xf0\x9f\x8c\xbf"forKey:@"[草]"];
      [dict setValue:@"\xf0\x9f\x8d\x92"forKey:@"[樱桃]"];
      [dict setValue:@"\xf0\x9f\x8d\x8c"forKey:@"[香蕉]"];
      [dict setValue:@"\xf0\x9f\x8d\x8e"forKey:@"[红苹果]"];
      [dict setValue:@"\xf0\x9f\x8d\x8a"forKey:@"[橘子]"];
      [dict setValue:@"\xf0\x9f\x8d\x93"forKey:@"[草莓]"];
      [dict setValue:@"\xf0\x9f\x8d\x89"forKey:@"[西瓜]"];
      [dict setValue:@"\xf0\x9f\x8d\x85"forKey:@"[番茄]"];
      [dict setValue:@"\xf0\x9f\x8d\x86"forKey:@"[茄子]"];
      [dict setValue:@"\xf0\x9f\x8d\x88"forKey:@"[甜瓜]"];
      [dict setValue:@"\xf0\x9f\x8d\x8d"forKey:@"[菠萝]"];
      [dict setValue:@"\xf0\x9f\x8d\x87"forKey:@"[葡萄]"];
      [dict setValue:@"\xf0\x9f\x8d\x91"forKey:@"[桃子]"];
      [dict setValue:@"\xf0\x9f\x8d\x8f"forKey:@"[青苹果]"];
      [dict setValue:@"\xf0\x9f\x91\x80"forKey:@"[眼睛]"];
      [dict setValue:@"\xf0\x9f\x91\x82"forKey:@"[耳朵]"];
      [dict setValue:@"\xf0\x9f\x91\x83"forKey:@"[鼻子]"];
      [dict setValue:@"\xf0\x9f\x91\x84"forKey:@"[口]"];
      [dict setValue:@"\xf0\x9f\x91\x85"forKey:@"[舌头]"];
      [dict setValue:@"\xf0\x9f\x92\x84"forKey:@"[口红]"];
      [dict setValue:@"\xf0\x9f\x92\x85"forKey:@"[指甲油]"];
      [dict setValue:@"\xf0\x9f\x92\x86"forKey:@"[面部按摩]"];
      [dict setValue:@"\xf0\x9f\x92\x87"forKey:@"[扣减]"];
      [dict setValue:@"\xf0\x9f\x92\x88"forKey:@"[理发店招牌]"];
      [dict setValue:@"\xf0\x9f\x91\xa4"forKey:@"[胸围的剪影]"];
      [dict setValue:@"\xf0\x9f\x91\xa6"forKey:@"[男孩]"];
      [dict setValue:@"\xf0\x9f\x91\xa7"forKey:@"[女孩]"];
      [dict setValue:@"\xf0\x9f\x91\xa8"forKey:@"[男人]"];
      [dict setValue:@"\xf0\x9f\x91\xa9"forKey:@"[女人]"];
      [dict setValue:@"\xf0\x9f\x91\xaa"forKey:@"[家庭]"];
      [dict setValue:@"\xf0\x9f\x91\xab"forKey:@"[牵着手]"];
      [dict setValue:@"\xf0\x9f\x91\xae"forKey:@"[警官]"];
      [dict setValue:@"\xf0\x9f\x91\xaf"forKey:@"[兔子耳朵的女人]"];
      [dict setValue:@"\xf0\x9f\x91\xb0"forKey:@"[新娘的面纱]"];
      [dict setValue:@"\xf0\x9f\x91\xb1"forKey:@"[人的金发]"];
      [dict setValue:@"\xf0\x9f\x91\xb2"forKey:@"[特别男人]"];
      [dict setValue:@"\xf0\x9f\x91\xb3"forKey:@"[男子头巾]"];
      [dict setValue:@"\xf0\x9f\x91\xb4"forKey:@"[老男人]"];
      [dict setValue:@"\xf0\x9f\x91\xb5"forKey:@"[老女人]"];
      [dict setValue:@"\xf0\x9f\x91\xb6"forKey:@"[宝宝]"];
      [dict setValue:@"\xf0\x9f\x91\xb7"forKey:@"[建筑工人]"];
      [dict setValue:@"\xf0\x9f\x91\xb8"forKey:@"[公主]"];
      [dict setValue:@"\xf0\x9f\x91\xb9"forKey:@"[日本食人魔]"];
      [dict setValue:@"\xf0\x9f\x91\xba"forKey:@"[日本小妖]"];
      [dict setValue:@"\xf0\x9f\x91\xbb"forKey:@"[幽灵]"];
      [dict setValue:@"\xf0\x9f\x91\xbC"forKey:@"[天使]"];
      [dict setValue:@"\xf0\x9f\x91\xbD"forKey:@"[外星人]"];
      [dict setValue:@"\xf0\x9f\x91\xbe"forKey:@"[怪物 ]"];
      [dict setValue:@"\xf0\x9f\x91\xbf"forKey:@"[小孩]"];
      [dict setValue:@"\xf0\x9f\x92\x80"forKey:@"[脑壳]"];
      [dict setValue:@"\xf0\x9f\x92\x81"forKey:@"[信息台人]"];
      [dict setValue:@"\xf0\x9f\x92\x82"forKey:@"[卫兵]"];
      [dict setValue:@"\xf0\x9f\x92\x83"forKey:@"[舞蹈演员]"];
      [dict setValue:@"\xf0\x9f\x90\x8c"forKey:@"[蜗牛]"];
      [dict setValue:@"\xf0\x9f\x90\x8d"forKey:@"[蛇]"];
      [dict setValue:@"\xf0\x9f\x90\x8e"forKey:@"[马]"];
      [dict setValue:@"\xf0\x9f\x90\x94"forKey:@"[鸡]" ];
      [dict setValue:@"\xf0\x9f\x90\x97"forKey:@"[野猪]"];
      [dict setValue:@"\xf0\x9f\x90\xab"forKey:@"[双峰驼]"];
      [dict setValue:@"\xf0\x9f\x90\x98"forKey:@"[大象]"];
      [dict setValue:@"\xf0\x9f\x90\xa8"forKey:@"[树袋熊]"];
      [dict setValue:@"\xf0\x9f\x90\x92"forKey:@"[猴子]"];
      [dict setValue:@"\xf0\x9f\x90\x91"forKey:@"[羊]"];
      [dict setValue:@"\xf0\x9f\x90\x99"forKey:@"[八达通]"];
      [dict setValue:@"\xf0\x9f\x90\x9a"forKey:@"[螺]"];
      [dict setValue:@"\xf0\x9f\x90\x9b"forKey:@"[鬼怪]"];
      [dict setValue:@"\xf0\x9f\x90\x9c"forKey:@"[ANT]"];
      [dict setValue:@"\xf0\x9f\x90\x9d"forKey:@"[蜜蜂]"];
      [dict setValue:@"\xf0\x9f\x90\x9e"forKey:@"[瓢虫]"];
      [dict setValue:@"\xf0\x9f\x90\xa0"forKey:@"[热带鱼]"];
      [dict setValue:@"\xf0\x9f\x90\xa1"forKey:@"[舞蹈健身操]"];
      [dict setValue:@"\xf0\x9f\x90\xa2"forKey:@"[龟]"];
      [dict setValue:@"\xf0\x9f\x90\xa4"forKey:@"[小鸡]"];
      [dict setValue:@"\xf0\x9f\x90\xa5"forKey:@"[面向前方的小鸡]"];
      [dict setValue:@"\xf0\x9f\x90\xa6"forKey:@"[bIRD]"];
      [dict setValue:@"\xf0\x9f\x90\xa3"forKey:@"[孵化小鸡]"];
      [dict setValue:@"\xf0\x9f\x90\xa7"forKey:@"[企鹅]"];
      [dict setValue:@"\xf0\x9f\x90\xa9"forKey:@"[贵宾犬]"];
      [dict setValue:@"\xf0\x9f\x90\x9f"forKey:@"[鱼]"];
      [dict setValue:@"\xf0\x9f\x90\xac"forKey:@"[海豚]"];
      [dict setValue:@"\xf0\x9f\x90\xaD"forKey:@"[小老鼠]"];
      [dict setValue:@"\xf0\x9f\x90\xaf"forKey:@"[老虎]"];
      [dict setValue:@"\xf0\x9f\x90\xb1"forKey:@"[猫脸]"];
      [dict setValue:@"\xf0\x9f\x90\xb3"forKey:@"[喷气的鲸鱼]"];
      [dict setValue:@"\xf0\x9f\x90\xb4"forKey:@"[马面]"];
      [dict setValue:@"\xf0\x9f\x90\xb5"forKey:@"[猴脸]"];
      [dict setValue:@"\xf0\x9f\x90\xb6"forKey:@"[狗脸]"];
      [dict setValue:@"\xf0\x9f\x90\xb7"forKey:@"[猪脸]"];
      [dict setValue:@"\xf0\x9f\x90\xbb"forKey:@"[熊脸]"];
      [dict setValue:@"\xf0\x9f\x90\xb9"forKey:@"[仓鼠脸]"];
      [dict setValue:@"\xf0\x9f\x90\xba"forKey:@"[狼脸]"];
      [dict setValue:@"\xf0\x9f\x90\xae"forKey:@"[牛脸]"];
      [dict setValue:@"\xf0\x9f\x90\xb0"forKey:@"[兔子脸]"];
      [dict setValue:@"\xf0\x9f\x90\xb8"forKey:@"[青蛙脸]"];
      [dict setValue:@"\xf0\x9f\x90\xbe"forKey:@"[脚印]"];
      [dict setValue:@"\xf0\x9f\x90\xb2"forKey:@"[龙面]"];
      [dict setValue:@"\xf0\x9f\x90\xbC"forKey:@"[熊猫脸]"];
      [dict setValue:@"\xf0\x9f\x90\xbD"forKey:@"[猪鼻子]"];
      [dict setValue:@"\xf0\x9f\x98\xa0"forKey:@"[很生气]"];
      [dict setValue:@"\xf0\x9f\x98\xa9"forKey:@"[疲惫]"];
      [dict setValue:@"\xf0\x9f\x98\xb2"forKey:@"[很惊讶]"];
      [dict setValue:@"\xf0\x9f\x98\x9e"forKey:@"[失望]"];
      [dict setValue:@"\xf0\x9f\x98\xb5"forKey:@"[头晕]"];
      [dict setValue:@"\xf0\x9f\x98\xb0"forKey:@"[张口冷汗]"];
      [dict setValue:@"\xf0\x9f\x98\x92"forKey:@"[不开心]"];
      [dict setValue:@"\xf0\x9f\x98\x8d"forKey:@"[微笑的脸与心形的眼睛]"];
      [dict setValue:@"\xf0\x9f\x98\xa4"forKey:@"[鼻子冒气]"];
      [dict setValue:@"\xf0\x9f\x98\x9c"forKey:@"[舌头和眨眼]"];
      [dict setValue:@"\xf0\x9f\x98\x9d"forKey:@"[舌头，紧紧地闭着眼睛]"];
      [dict setValue:@"\xf0\x9f\x98\x8b"forKey:@"[澄怀味美味的食物]"];
      [dict setValue:@"\xf0\x9f\x98\x98"forKey:@"[亲吻]"];
      [dict setValue:@"\xf0\x9f\x98\x9a"forKey:@"[亲吻脸，闭只眼]"];
      [dict setValue:@"\xf0\x9f\x98\xb7"forKey:@"[医疗]"];
      [dict setValue:@"\xf0\x9f\x98\xb3"forKey:@"[红扑扑的脸蛋]"];
      [dict setValue:@"\xf0\x9f\x98\x83"forKey:@"[笑脸张开嘴]"];
      [dict setValue:@"\xf0\x9f\x98\x85"forKey:@"[笑脸张口冷汗]"];
      [dict setValue:@"\xf0\x9f\x98\x86"forKey:@"[笑脸张开嘴，紧紧地闭只眼]"];
      [dict setValue:@"\xf0\x9f\x98\x81"forKey:@"[笑嘻嘻面带微笑的眼睛]"];
      [dict setValue:@"\xf0\x9f\x98\x82"forKey:@"[面带喜悦的泪水]"];
      [dict setValue:@"\xf0\x9f\x98\x8a"forKey:@"[微笑的脸，含笑的眼睛]"];
      [dict setValue:@"\xf0\x9f\x98\x84"forKey:@"[张开嘴微笑的脸，含笑的眼睛]"];
      [dict setValue:@"\xf0\x9f\x98\xa2"forKey:@"[哭脸]"];
      [dict setValue:@"\xf0\x9f\x98\xaD"forKey:@"[大声些哭泣的脸]"];
      [dict setValue:@"\xf0\x9f\x98\xa8"forKey:@"[可怕]"];
      [dict setValue:@"\xf0\x9f\x98\xa3"forKey:@"[怎奈]"];
      [dict setValue:@"\xf0\x9f\x98\xa1"forKey:@"[撅]"];
      [dict setValue:@"\xf0\x9f\x98\x8c"forKey:@"[松了一口气]"];
      [dict setValue:@"\xf0\x9f\x98\x96"forKey:@"[混淆]"];
      [dict setValue:@"\xf0\x9f\x98\x94"forKey:@"[郁郁不乐的]"];
      [dict setValue:@"\xf0\x9f\x98\xb1"forKey:@"[恐惧中尖叫]"];
      [dict setValue:@"\xf0\x9f\x98\xaa"forKey:@"[想睡觉]"];
      [dict setValue:@"\xf0\x9f\x98\x8f"forKey:@"[奸笑]"];
      [dict setValue:@"\xf0\x9f\x98\x93"forKey:@"[冷汗]"];
      [dict setValue:@"\xf0\x9f\x98\xa5"forKey:@"[失望，但宽慰]"];
      [dict setValue:@"\xf0\x9f\x98\xab"forKey:@"[疲惫的脸]"];
      [dict setValue:@"\xf0\x9f\x98\x89"forKey:@"[眨眼表情]"];
      [dict setValue:@"\xf0\x9f\x98\xba"forKey:@"[张开嘴微笑的脸猫]"];
      [dict setValue:@"\xf0\x9f\x98\xb8"forKey:@"[嘻嘻]"];
      [dict setValue:@"\xf0\x9f\x98\xb9"forKey:@"[泪花]"];
      [dict setValue:@"\xf0\x9f\x98\xbD"forKey:@"[接吻猫脸，闭只眼]"];
      [dict setValue:@"\xf0\x9f\x98\xbb"forKey:@"[心形的眼睛，微笑的脸猫]"];
      [dict setValue:@"\xf0\x9f\x98\xbf"forKey:@"[哭脸猫]"];
      [dict setValue:@"\xf0\x9f\x98\xbe"forKey:@"[撅嘴脸猫]"];
      [dict setValue:@"\xf0\x9f\x98\xbC"forKey:@"[面带苦笑]"];
      [dict setValue:@"\xf0\x9f\x99\x80"forKey:@"[疲惫的脸猫]"];
      [dict setValue:@"\xf0\x9f\x99\x85"forKey:@"[不好]"];
      [dict setValue:@"\xf0\x9f\x99\x86"forKey:@"[OK的手势]"];
//      [dict setValue:@"\xf0\x9f\x99\x87却"forKey:@"[人鞠躬深度]"];
      [dict setValue:@"\xf0\x9f\x99\x88"forKey:@"[猴子]"];
      [dict setValue:@"\xf0\x9f\x99\x8a"forKey:@"[说NO ]"];
      [dict setValue:@"\xf0\x9f\x99\x89"forKey:@"[听到]"];
      [dict setValue:@"\xf0\x9f\x99\x8b"forKey:@"[举一个手]"];
      [dict setValue:@"\xf0\x9f\x99\x8c"forKey:@"[举两个手]"];
      [dict setValue:@"\xf0\x9f\x99\x8d"forKey:@"[皱着眉头]"];
      [dict setValue:@"\xf0\x9f\x99\x8e"forKey:@"[撅嘴]"];
      [dict setValue:@"\xf0\x9f\x99\x8f"forKey:@"[双手合十]"];
      [dict setValue:@"\xf0\x9f\x8f\xa0"forKey:@"[房屋建筑]"];
      [dict setValue:@"\xf0\x9f\x8f\xa1"forKey:@"[花园住宅"];
      [dict setValue:@"\xf0\x9f\x8f\xa2"forKey:@"[办公建筑]"];
      [dict setValue:@"\xf0\x9f\x8f\xa3"forKey:@"[日本邮政]"];
      [dict setValue:@"\xf0\x9f\x8f\xa5"forKey:@"[医院]"];
      [dict setValue:@"\xf0\x9f\x8f\xa6"forKey:@"[银行]"];
      [dict setValue:@"\xf0\x9f\x8f\xa7"forKey:@"[自动取款机]"];
      [dict setValue:@"\xf0\x9f\x8f\xa8"forKey:@"[酒店]"];
      [dict setValue:@"\xf0\x9f\x8f\xa9"forKey:@"[爱情公寓L]"];
      [dict setValue:@"\xf0\x9f\x8f\xaa"forKey:@"[便利商店]"];
      [dict setValue:@"\xf0\x9f\x8f\xab"forKey:@"[学校]"];
      [dict setValue:@"\xe2\x9b\xaa"forKey:@"[堂]"];
      [dict setValue:@"\xe2\x9b\xb2"forKey:@"[喷泉]"];
      [dict setValue:@"\xf0\x9f\x8f\xac"forKey:@"[百货]"];
      [dict setValue:@"\xf0\x9f\x8f\xaf"forKey:@"[日本城堡]"];
      [dict setValue:@"\xf0\x9f\x8f\xb0"forKey:@"[欧洲城堡]"];
      [dict setValue:@"\xf0\x9f\x8f\xaD"forKey:@"[工厂]"];
      [dict setValue:@"\xe2\x9a\x93"forKey:@"[锚]"];
      [dict setValue:@"\xf0\x9f\x8f\xae"forKey:@"[居酒屋]"];
      [dict setValue:@"\xf0\x9f\x97\xbb"forKey:@"[富士山]"];
      [dict setValue:@"\xf0\x9f\x97\xbC"forKey:@"[东京塔]"];
      [dict setValue:@"\xf0\x9f\x97\xbD"forKey:@"[自由女神像"];
      [dict setValue:@"\xf0\x9f\x97\xbe"forKey:@"[人影日本]"];
//      [dict setValue:@"\xf0\x9f\x97\xbf"forKey:@"[MOYaI]"];
      [dict setValue:@"\xf0\x9f\x91\x9e"forKey:@"[芒鞋]"];
      [dict setValue:@"\xf0\x9f\x91\x9f"forKey:@"[运动鞋]"];
      [dict setValue:@"\xf0\x9f\x91\xa0"forKey:@"[高跟鞋]"];
      [dict setValue:@"\xf0\x9f\x91\xa1"forKey:@"[女人的凉鞋]"];
      [dict setValue:@"\xf0\x9f\x91\xa2"forKey:@"[女人的靴子]"];
      [dict setValue:@"\xf0\x9f\x91\xa3"forKey:@"[足迹]"];
      [dict setValue:@"\xf0\x9f\x91\x93"forKey:@"[眼镜]"];
      [dict setValue:@"\xf0\x9f\x91\x95"forKey:@"[T-SHIRT]"];
      [dict setValue:@"\xf0\x9f\x91\x96"forKey:@"[牛仔裤]"];
      [dict setValue:@"\xf0\x9f\x91\x91"forKey:@"[冠]"];
      [dict setValue:@"\xf0\x9f\x91\x94"forKey:@"[领带]"];
      [dict setValue:@"\xf0\x9f\x91\x92"forKey:@"[女人的帽子]"];
      [dict setValue:@"\xf0\x9f\x91\x97"forKey:@"[礼服]"];
      [dict setValue:@"\xf0\x9f\x91\x98"forKey:@"[和服]"];
      [dict setValue:@"\xf0\x9f\x91\x99"forKey:@"[比基尼]"];
      [dict setValue:@"\xf0\x9f\x91\x9a"forKey:@"[女人的衣服]"];
      [dict setValue:@"\xf0\x9f\x91\x9b"forKey:@"[钱包]"];
      [dict setValue:@"\xf0\x9f\x91\x9c"forKey:@"[手袋]"];
      [dict setValue:@"\xf0\x9f\x91\x9d"forKey:@"[袋]"];
      [dict setValue:@"\xf0\x9f\x92\xb0"forKey:@"[钱袋子]"];
      [dict setValue:@"\xf0\x9f\x92\xb1"forKey:@"[货币兑换]"];
      [dict setValue:@"\xf0\x9f\x92\xb9"forKey:@"[上升趋势]"];
      [dict setValue:@"\xf0\x9f\x92\xb2"forKey:@"[美元]"];
      [dict setValue:@"\xf0\x9f\x92\xb3"forKey:@"[信用卡]"];
      [dict setValue:@"\xf0\x9f\x92\xb4"forKey:@"[日元]"];
//      [dict setValue:@"\xf0\x9f\x92\xb5"forKey:@"[美元]"];
      [dict setValue:@"\xf0\x9f\x92\xb8"forKey:@"[长着翅膀的钱]"];
      [dict setValue:@"\xf0\x9f\x87\xa8\xf0\x9f\x87\xb3"forKey:@"[区域指示符号字母CN]"];
      [dict setValue:@"\xf0\x9f\x87\xa9\xf0\x9f\x87\xaa"forKey:@"[区域指示符号字母De]"];
      [dict setValue:@"\xf0\x9f\x87\xaa\xf0\x9f\x87\xb8"forKey:@"[符号填写区域指标eS]"];
      [dict setValue:@"\xf0\x9f\x87\xab\xf0\x9f\x87\xb7"forKey:@"[符号填写区域指标fR]"];
      [dict setValue:@"\xf0\x9f\x87\xac\xf0\x9f\x87\xa7"forKey:@"[符号填写区域指标Gb]"];
      [dict setValue:@"\xf0\x9f\x87\xae\xf0\x9f\x87\xb9"forKey:@"[区域指示符号字母IT]"];
      [dict setValue:@"\xf0\x9f\x87\xaf\xf0\x9f\x87\xb5"forKey:@"[符号填写区域指标JP]"];
      [dict setValue:@"\xf0\x9f\x87\xb0\xf0\x9f\x87\xb7"forKey:@"[区域指示符号字母KR]"];
      [dict setValue:@"\xf0\x9f\x87\xb7\xf0\x9f\x87\xba"forKey:@"[区域指示符号字母RU]"];
      [dict setValue:@"\xf0\x9f\x87\xba\xf0\x9f\x87\xb8"forKey:@"[符号填写区域指标美国]"];
      [dict setValue:@"\xf0\x9f\x94\xa5"forKey:@"[火]"];
      [dict setValue:@"\xf0\x9f\x94\xa6"forKey:@"[手电筒]"];
      [dict setValue:@"\xf0\x9f\x94\xa7"forKey:@"[扳手]"];
      [dict setValue:@"\xf0\x9f\x94\xa8"forKey:@"[锤]"];
      [dict setValue:@"\xf0\x9f\x94\xa9"forKey:@"[螺母和螺栓]"];
//      [dict setValue:@"\xf0\x9f\x94\xaa"forKey:@"[HOCHO]"];
      [dict setValue:@"\xf0\x9f\x94\xab"forKey:@"[手枪]"];
      [dict setValue:@"\xf0\x9f\x94\xae"forKey:@"[水晶球]"];
      [dict setValue:@"\xf0\x9f\x94\xaf"forKey:@"[五角星中间点]"];
      [dict setValue:@"\xf0\x9f\x94\xb0"forKey:@"[日本]"];
      [dict setValue:@"\xf0\x9f\x94\xb1"forKey:@"[三叉戟徽]"];
      [dict setValue:@"\xf0\x9f\x92\x89"forKey:@"[注射器]"];
      [dict setValue:@"\xf0\x9f\x92\x8a"forKey:@"[丸]"];
      [dict setValue:@"\xf0\x9f\x85\xb0"forKey:@"[大写拉丁字母a]"];
      [dict setValue:@"\xf0\x9f\x85\xb1"forKey:@"[大写拉丁字母b]"];
      [dict setValue:@"\xf0\x9f\x86\x8e"forKey:@"[负]"];
      [dict setValue:@"\xf0\x9f\x85\xbe"forKey:@"[负平方的拉丁大写字母O]"];
      [dict setValue:@"\xf0\x9f\x8e\x80"forKey:@"[丝带]"];
      [dict setValue:@"\xf0\x9f\x8e\x81"forKey:@"[礼物]"];
      [dict setValue:@"\xf0\x9f\x8e\x82"forKey:@"[生日蛋糕"];
      [dict setValue:@"\xf0\x9f\x8e\x84"forKey:@"[大圣诞树]"];
      [dict setValue:@"\xf0\x9f\x8e\x85"forKey:@"[圣诞老人"];
      [dict setValue:@"\xf0\x9f\x8e\x8c"forKey:@"[旗帜]"];
      [dict setValue:@"\xf0\x9f\x8e\x86"forKey:@"[烟火]"];
      [dict setValue:@"\xf0\x9f\x8e\x88"forKey:@"[气球]"];
      [dict setValue:@"\xf0\x9f\x8e\x89"forKey:@"[党校波普尔]"];
      [dict setValue:@"\xf0\x9f\x8e\x8d"forKey:@"[松装饰]"];
      [dict setValue:@"\xf0\x9f\x8e\x8e"forKey:@"[日本娃娃]"];
      [dict setValue:@"\xf0\x9f\x8e\x93"forKey:@"[毕业帽]"];
      [dict setValue:@"\xf0\x9f\x8e\x92"forKey:@"[学生书包]"];
      [dict setValue:@"\xf0\x9f\x8e\x8f"forKey:@"[鲤鱼旗"];
      [dict setValue:@"\xf0\x9f\x8e\x87"forKey:@"[焰火]"];
      [dict setValue:@"\xf0\x9f\x8e\x90"forKey:@"[风铃]"];
      [dict setValue:@"\xf0\x9f\x8e\x83"forKey:@"[南瓜灯]"];
      [dict setValue:@"\xf0\x9f\x8e\x8a"forKey:@"[五彩纸屑球]"];
      [dict setValue:@"\xf0\x9f\x8e\x8b"forKey:@"[七夕树]"];
      [dict setValue:@"\xf0\x9f\x8e\x91"forKey:@"[赏月典礼]"];
      [dict setValue:@"\xf0\x9f\x93\x9f"forKey:@"[寻呼机]"];
      [dict setValue:@"\xe2\x98\x8e"forKey:@"[回电话]"];
      [dict setValue:@"\xf0\x9f\x93\x9e"forKey:@"[电话听筒"];
      [dict setValue:@"\xf0\x9f\x93\xb1"forKey:@"[手机]"];
      [dict setValue:@"\xf0\x9f\x93\xb2"forKey:@"[手机与向右箭头]"];
      [dict setValue:@"\xf0\x9f\x93\x9d"forKey:@"[备忘录]"];
      [dict setValue:@"\xf0\x9f\x93\xa0"forKey:@"[传真机]"];
      [dict setValue:@"\xe2\x9c\x89"forKey:@"[信封]"];
      [dict setValue:@"\xf0\x9f\x93\xa8"forKey:@"[来电]"];
      [dict setValue:@"\xf0\x9f\x93\xa9"forKey:@"[信封朝下]"];
      [dict setValue:@"\xf0\x9f\x93\xaa"forKey:@"[降低]"];
      [dict setValue:@"\xf0\x9f\x93\xab"forKey:@"[提高]"];
      [dict setValue:@"\xf0\x9f\x93\xae"forKey:@"[企业邮箱]"];
      [dict setValue:@"\xf0\x9f\x93\xb0"forKey:@"[报纸]"];
      [dict setValue:@"\xf0\x9f\x93\xa2"forKey:@"[扩音喇叭]"];
      [dict setValue:@"\xf0\x9f\x93\xa3"forKey:@"[喊话]"];
      [dict setValue:@"\xf0\x9f\x93\xa1"forKey:@"[卫星天线]"];
      [dict setValue:@"\xf0\x9f\x93\xa4"forKey:@"[发件箱]"];
      [dict setValue:@"\xf0\x9f\x93\xa5"forKey:@"[收件箱]"];
      [dict setValue:@"\xf0\x9f\x93\xa6"forKey:@"[包装]"];
      [dict setValue:@"\xf0\x9f\x93\xa7"forKey:@"[电子邮件]"];
      [dict setValue:@"\xf0\x9f\x94\xa0"forKey:@"[拉丁大写字母或]"];
      [dict setValue:@"\xf0\x9f\x94\xa1"forKey:@"[拉丁小写字母输入]"];
      [dict setValue:@"\xf0\x9f\x94\xa2"forKey:@"[输入]"];
//      [dict setValue:@"\xf0\x9f\x94\xa3"forKey:@"[的符号输入符号]"];
      [dict setValue:@"\xf0\x9f\x94\xa4"forKey:@"[输入符号的拉丁字母]"];
      [dict setValue:@"\xe2\x9c\x92"forKey:@"[黑笔尖]"];
      [dict setValue:@"\xf0\x9f\x92\xba"forKey:@"[座位]"];
      [dict setValue:@"\xf0\x9f\x92\xbb"forKey:@"[个人电脑]"];
      [dict setValue:@"\xe2\x9c\x8f"forKey:@"[铅笔]"];
      [dict setValue:@"\xf0\x9f\x93\x8e"forKey:@"[回形针"];
      [dict setValue:@"\xf0\x9f\x92\xbC"forKey:@"[公文包]"];
      [dict setValue:@"\xf0\x9f\x92\xbD"forKey:@"[录音机]"];
      [dict setValue:@"\xf0\x9f\x92\xbe"forKey:@"[软盘]"];
      [dict setValue:@"\xf0\x9f\x92\xbf"forKey:@"[光盘]"];
      [dict setValue:@"\xf0\x9f\x93\x80"forKey:@"[DVD]"];
      [dict setValue:@"\xe2\x9c\x82"forKey:@"[剪刀]"];
      [dict setValue:@"\xf0\x9f\x93\x8d"forKey:@"[图钉]"];
      [dict setValue:@"\xf0\x9f\x93\x83"forKey:@"[卷曲]"];
      [dict setValue:@"\xf0\x9f\x93\x84"forKey:@"[页朝上]"];
      [dict setValue:@"\xf0\x9f\x93\x85"forKey:@"[日历]"];
      [dict setValue:@"\xf0\x9f\x93\x81"forKey:@"[文件的文件夹]"];
      [dict setValue:@"\xf0\x9f\x93\x82"forKey:@"[打开文件夹]"];
      [dict setValue:@"\xf0\x9f\x93\x93"forKey:@"[笔记本]"];
      [dict setValue:@"\xf0\x9f\x93\x96"forKey:@"[打开的书]"];
      [dict setValue:@"\xf0\x9f\x93\x94"forKey:@"[笔记本]"];
      [dict setValue:@"\xf0\x9f\x93\x95"forKey:@"[合着的书]"];
      [dict setValue:@"\xf0\x9f\x93\x97"forKey:@"[绿皮书]"];
      [dict setValue:@"\xf0\x9f\x93\x98"forKey:@"[蓝皮书]"];
      [dict setValue:@"\xf0\x9f\x93\x99"forKey:@"[黄皮书]"];
      [dict setValue:@"\xf0\x9f\x93\x9a"forKey:@"[读书]"];
      [dict setValue:@"\xf0\x9f\x93\x9b"forKey:@"[胸牌]"];
      [dict setValue:@"\xf0\x9f\x93\x9c"forKey:@"[滚动]"];
      [dict setValue:@"\xf0\x9f\x93\x8b"forKey:@"[剪贴簿]"];
      [dict setValue:@"\xf0\x9f\x93\x86"forKey:@"[日历]"];
      [dict setValue:@"\xf0\x9f\x93\x8a"forKey:@"[酒吧]"];
      [dict setValue:@"\xf0\x9f\x93\x88"forKey:@"[向上的趋势图表]"];
      [dict setValue:@"\xf0\x9f\x93\x89"forKey:@"[下调趋势]"];
      [dict setValue:@"\xf0\x9f\x93\x87"forKey:@"[上证指数]"];
      [dict setValue:@"\xf0\x9f\x93\x8c"forKey:@"[图钉]"];
      [dict setValue:@"\xf0\x9f\x93\x92"forKey:@"[分类帐]"];
      [dict setValue:@"\xf0\x9f\x93\x8f"forKey:@"[直尺]"];
      [dict setValue:@"\xf0\x9f\x93\x90"forKey:@"[三角尺]"];
      [dict setValue:@"\xf0\x9f\x93\x91"forKey:@"[收藏]"];
      [dict setValue:@"\xf0\x9f\x8e\xbD"forKey:@"[衬衫]"];
      [dict setValue:@"\xe2\x9a\xbe"forKey:@"[棒球]"];
      [dict setValue:@"\xe2\x9b\xb3"forKey:@"[国旗]"];
      [dict setValue:@"\xf0\x9f\x8e\xbe"forKey:@"[网球球拍和球]"];
      [dict setValue:@"\xe2\x9a\xbD"forKey:@"[足球]"];
      [dict setValue:@"\xf0\x9f\x8e\xbf"forKey:@"[滑雪板]"];
      [dict setValue:@"\xf0\x9f\x8f\x80"forKey:@"[篮球]"];
      [dict setValue:@"\xf0\x9f\x8f\x81"forKey:@"[格子旗旗]"];
      [dict setValue:@"\xf0\x9f\x8f\x82"forKey:@"[滑雪板]"];
      [dict setValue:@"\xf0\x9f\x8f\x83"forKey:@"[跑]"];
      [dict setValue:@"\xf0\x9f\x8f\x84"forKey:@"[冲浪者]"];
      [dict setValue:@"\xf0\x9f\x8f\x86"forKey:@"[杯]"];
      [dict setValue:@"\xf0\x9f\x8f\x88"forKey:@"[美式足球]"];
      [dict setValue:@"\xf0\x9f\x8f\x8a"forKey:@"[游泳者"];
      [dict setValue:@"\xf0\x9f\x9a\x83"forKey:@"[轨道车]"];
      [dict setValue:@"\xf0\x9f\x9a\x87"forKey:@"[麦德龙]"];
      [dict setValue:@"\xe2\x93\x82"forKey:@"[M]"];
      [dict setValue:@"\xf0\x9f\x9a\x84"forKey:@"[列车]"];
      [dict setValue:@"\xf0\x9f\x9a\x85"forKey:@"[子弹头列车]"];
      [dict setValue:@"\xf0\x9f\x9a\x97"forKey:@"[汽车]"];
      [dict setValue:@"\xf0\x9f\x9a\x99"forKey:@"[休闲车]"];
      [dict setValue:@"\xf0\x9f\x9a\x8c"forKey:@"[公共汽车]"];
      [dict setValue:@"\xf0\x9f\x9a\x8f"forKey:@"[公共汽车站]"];
      [dict setValue:@"\xf0\x9f\x9a\xa2"forKey:@"[船舶]"];
      [dict setValue:@"\xe2\x9c\x88"forKey:@"[飞机]"];
      [dict setValue:@"\xe2\x9b\xb5"forKey:@"[帆船]"];
      [dict setValue:@"\xf0\x9f\x9a\x89"forKey:@"[站]"];
      [dict setValue:@"\xf0\x9f\x9a\x80"forKey:@"[火箭]"];
      [dict setValue:@"\xf0\x9f\x9a\xa4"forKey:@"[快艇]"];
      [dict setValue:@"\xf0\x9f\x9a\x95"forKey:@"[出租车]"];
      [dict setValue:@"\xf0\x9f\x9a\x9a"forKey:@"[送货车]"];
      [dict setValue:@"\xf0\x9f\x9a\x92"forKey:@"[消防车]"];
      [dict setValue:@"\xf0\x9f\x9a\x91"forKey:@"[救护车]"];
      [dict setValue:@"\xf0\x9f\x9a\x93"forKey:@"[警车]"];
      [dict setValue:@"\xe2\x9b\xbD"forKey:@"[燃油泵]"];
      [dict setValue:@"\xf0\x9f\x85\xbf"forKey:@"[拉丁大写字母P]"];
      [dict setValue:@"\xf0\x9f\x9a\xa5"forKey:@"[水平]"];
      [dict setValue:@"\xf0\x9f\x9a\xa7"forKey:@"[建筑]"];
      [dict setValue:@"\xf0\x9f\x9a\xa8"forKey:@"[旋转灯的警车]"];
      [dict setValue:@"\xe2\x99\xa8"forKey:@"[温泉]"];
      [dict setValue:@"\xe2\x9b\xba"forKey:@"[帐篷]"];
      [dict setValue:@"\xf0\x9f\x8e\xa0"forKey:@"[旋转木马]"];
      [dict setValue:@"\xf0\x9f\x8e\xa1"forKey:@"[摩天轮]"];
      [dict setValue:@"\xf0\x9f\x8e\xa2"forKey:@"[过山车]"];
      [dict setValue:@"\xf0\x9f\x8e\xa3"forKey:@"[鱼竿和鱼]"];
      [dict setValue:@"\xf0\x9f\x8e\xa4"forKey:@"[麦克风]"];
      [dict setValue:@"\xf0\x9f\x8e\xa5"forKey:@"[摄像机]"];
      [dict setValue:@"\xf0\x9f\x8e\xa6"forKey:@"[电影]"];
      [dict setValue:@"\xf0\x9f\x8e\xa7"forKey:@"[耳机]"];
      [dict setValue:@"\xf0\x9f\x8e\xa8"forKey:@"[艺术家调色板]"];
      [dict setValue:@"\xf0\x9f\x8e\xa9"forKey:@"[大礼帽]"];
      [dict setValue:@"\xf0\x9f\x8e\xaa"forKey:@"[马戏团的帐篷]"];
      [dict setValue:@"\xf0\x9f\x8e\xab"forKey:@"[票]"];
      [dict setValue:@"\xf0\x9f\x8e\xac"forKey:@"[梆子董事会]"];
      [dict setValue:@"\xf0\x9f\x8e\xaD"forKey:@"[表演艺术]"];
      [dict setValue:@"\xf0\x9f\x8e\xae"forKey:@"[游戏]"];
      [dict setValue:@"\xf0\x9f\x80\x84"forKey:@"[麻将牌]"];
      [dict setValue:@"\xf0\x9f\x8e\xaf"forKey:@"[直接打]"];
      [dict setValue:@"\xf0\x9f\x8e\xb0"forKey:@"[老虎机"];
      [dict setValue:@"\xf0\x9f\x8e\xb1"forKey:@"[台球]"];
      [dict setValue:@"\xf0\x9f\x8e\xb2"forKey:@"[游戏]"];
      [dict setValue:@"\xf0\x9f\x8e\xb3"forKey:@"[保龄球]"];
      [dict setValue:@"\xf0\x9f\x8e\xb4"forKey:@"[扑克牌]"];
      [dict setValue:@"\xf0\x9f\x83\x8f"forKey:@"[扑克牌黑]"];
      [dict setValue:@"\xf0\x9f\x8e\xb5"forKey:@"[音符]"];
      [dict setValue:@"\xf0\x9f\x8e\xb6"forKey:@"[的多重音符]"];
      [dict setValue:@"\xf0\x9f\x8e\xb7"forKey:@"[萨克斯管]"];
      [dict setValue:@"\xf0\x9f\x8e\xb8"forKey:@"[吉他]"];
      [dict setValue:@"\xf0\x9f\x8e\xb9"forKey:@"[音乐键盘]"];
      [dict setValue:@"\xf0\x9f\x8e\xba"forKey:@"[喇叭]"];
      [dict setValue:@"\xf0\x9f\x8e\xbb"forKey:@"[小提琴]"];
      [dict setValue:@"\xf0\x9f\x8e\xbC"forKey:@"[乐谱]"];
      [dict setValue:@"\xe3\x80\xbD"forKey:@"[部分药品评价]"];
      [dict setValue:@"\xf0\x9f\x93\xb7"forKey:@"[相机]"];
      [dict setValue:@"\xf0\x9f\x93\xb9"forKey:@"[摄像机]"];
      [dict setValue:@"\xf0\x9f\x93\xba"forKey:@"[电视]"];
      [dict setValue:@"\xf0\x9f\x93\xbb"forKey:@"[广播]"];
      [dict setValue:@"\xf0\x9f\x93\xbC"forKey:@"[录像带]"];
      [dict setValue:@"\xf0\x9f\x92\x8b"forKey:@"[吻痕]"];
      [dict setValue:@"\xf0\x9f\x92\x8c"forKey:@"[爱情信]"];
      [dict setValue:@"\xf0\x9f\x92\x8d"forKey:@"[环]"];
      [dict setValue:@"\xf0\x9f\x92\x8e"forKey:@"[宝石]"];
      [dict setValue:@"\xf0\x9f\x92\x8f"forKey:@"[深吻]"];
//      [dict setValue:@"\xf0\x9f\x92\x90"forKey:@"[bOUQUeT]"];
      [dict setValue:@"\xf0\x9f\x92\x91"forKey:@"[夫妇]"];
      [dict setValue:@"\xf0\x9f\x92\x92"forKey:@"[婚礼]"];
      [dict setValue:@"\xf0\x9f\x94\x9e"forKey:@"[未满十八]"];
      [dict setValue:@"\xC2\xa9"forKey:@"[版权]"];
      [dict setValue:@"\xC2\xae"forKey:@"[注册标记]"];
      [dict setValue:@"\xe2\x84\xa2"forKey:@"[商标标志]"];
      [dict setValue:@"\xe2\x84\xb9"forKey:@"[信息来源]"];
//      [dict setValue:@"＃\xe2\x83\xa3"forKey:@"[HaSH KeY]"];
      [dict setValue:@"1\xe2\x83\xa3"forKey:@"[键帽 1]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 2]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 3]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 4]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 5]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 6]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 7]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 8]"];
      [dict setValue:@"\xe2\x83\xa3"forKey:@"[键帽 9]"];
      [dict setValue:@"0\xe2\x83\xa3"forKey:@"[键帽 0]"];
      [dict setValue:@"\xf0\x9f\x94\x9f"forKey:@"[键帽 10]"];
      [dict setValue:@"\xf0\x9f\x93\xb6"forKey:@"[天线，酒吧]"];
      [dict setValue:@"\xf0\x9f\x93\xb3"forKey:@"[振动模式]"];
      [dict setValue:@"\xf0\x9f\x93\xb4"forKey:@"[手机关机]"];
      [dict setValue:@"\xf0\x9f\x8d\x94"forKey:@"[汉堡]"];
      [dict setValue:@"\xf0\x9f\x8d\x99"forKey:@"[饭团]"];
      [dict setValue:@"\xf0\x9f\x8d\xb0"forKey:@"[酥饼]"];
      [dict setValue:@"\xf0\x9f\x8d\x9c"forKey:@"[热气腾腾]"];
      [dict setValue:@"\xf0\x9f\x8d\x9e"forKey:@"[面包]"];
      [dict setValue:@"\xf0\x9f\x8d\xb3"forKey:@"[烹调]"];
      [dict setValue:@"\xf0\x9f\x8d\xa6"forKey:@"[软冰淇淋]"];
      [dict setValue:@"\xf0\x9f\x8d\x9f"forKey:@"[薯条]"];
      [dict setValue:@"\xf0\x9f\x8d\xa1"forKey:@"[花样男子]"];
      [dict setValue:@"\xf0\x9f\x8d\x98"forKey:@"[米果]"];
      [dict setValue:@"\xf0\x9f\x8d\x9a"forKey:@"[夹生饭]"];
      [dict setValue:@"\xf0\x9f\x8d\x9d"forKey:@"[意大利面条]"];
      [dict setValue:@"\xf0\x9f\x8d\x9b"forKey:@"[咖喱饭]"];
      [dict setValue:@"\xf0\x9f\x8d\xa2"forKey:@"[奥登]"];
      [dict setValue:@"\xf0\x9f\x8d\xa3"forKey:@"[寿司]"];
      [dict setValue:@"\xf0\x9f\x8d\xb1"forKey:@"[便当盒]"];
      [dict setValue:@"\xf0\x9f\x8d\xb2"forKey:@"[一盆食品]"];
      [dict setValue:@"\xf0\x9f\x8d\xa7"forKey:@"[刨冰]"];
      [dict setValue:@"\xf0\x9f\x8d\x96"forKey:@"[肉骨头]"];
      [dict setValue:@"\xf0\x9f\x8d\xa5"forKey:@"[蛋糕]"];
      [dict setValue:@"\xf0\x9f\x8d\xa0"forKey:@"[烤甘薯]"];
      [dict setValue:@"\xf0\x9f\x8d\x95"forKey:@"[披萨饼]"];
      [dict setValue:@"\xf0\x9f\x8d\x97"forKey:@"[家禽专家组]"];
      [dict setValue:@"\xf0\x9f\x8d\xa8"forKey:@"[冰淇淋]"];
      [dict setValue:@"\xf0\x9f\x8d\xa9"forKey:@"[圆环]"];
      [dict setValue:@"\xf0\x9f\x8d\xaa"forKey:@"[饼干]"];
      [dict setValue:@"\xf0\x9f\x8d\xab"forKey:@"[巧克力棒]"];
      [dict setValue:@"\xf0\x9f\x8d\xac"forKey:@"[糖果]"];
      [dict setValue:@"\xf0\x9f\x8d\xaD"forKey:@"[棒棒糖]"];
      [dict setValue:@"\xf0\x9f\x8d\xae"forKey:@"[吉士]"];
      [dict setValue:@"\xf0\x9f\x8d\xaf"forKey:@"[蜜罐]"];
      [dict setValue:@"\xf0\x9f\x8d\xa4"forKey:@"[炒虾仁]"];
      [dict setValue:@"\xf0\x9f\x8d\xb4"forKey:@"[刀叉]"];
      [dict setValue:@"\xe2\x98\x95"forKey:@"[热饮料]"];
      [dict setValue:@"\xf0\x9f\x8d\xb8"forKey:@"[鸡尾酒杯]"];
      [dict setValue:@"\xf0\x9f\x8d\xba"forKey:@"[啤酒杯]"];
      [dict setValue:@"\xf0\x9f\x8d\xb5"forKey:@"[无把手的茶杯]"];
      [dict setValue:@"\xf0\x9f\x8d\xb6"forKey:@"[瓶子和杯子]"];
      [dict setValue:@"\xf0\x9f\x8d\xb7"forKey:@"[酒杯]"];
      [dict setValue:@"\xf0\x9f\x8d\xbb"forKey:@"[啤酒]"];
      [dict setValue:@"\xf0\x9f\x8d\xb9"forKey:@"[饮料]"];
      [dict setValue:@"\xe2\x86\x97"forKey:@"[北东]"];
      [dict setValue:@"\xe2\x86\x98"forKey:@"[南东]"];
      [dict setValue:@"\xe2\x86\x96"forKey:@"[北西]"];
      [dict setValue:@"\xe2\x86\x99"forKey:@"[西南]"];
      [dict setValue:@"\xe2\xa4\xb4"forKey:@"[箭头向右弯曲向上]"];
      [dict setValue:@"\xe2\xa4\xb5"forKey:@"[箭头向右然后弯曲]"];
      [dict setValue:@"\xe2\x86\x94"forKey:@"[左右箭头]"];
      [dict setValue:@"\xe2\x86\x95"forKey:@"[向上向下的箭头]"];
      [dict setValue:@"\xe2\xac\x86"forKey:@"[隐私权|黑色箭头]"];
//      [dict setValue:@"\xe2\xac\x87却"forKey:@"[向下黑色箭头]"];
      [dict setValue:@"\xe2\x9e\xa1"forKey:@"[向右箭头]"];
      [dict setValue:@"\xe2\xac\x85"forKey:@"[向左黑色箭头]"];
      [dict setValue:@"\xe2\x96\xb6"forKey:@"[向右指的三角形]"];
      [dict setValue:@"\xe2\x97\x80"forKey:@"[向左的三角形]"];
      [dict setValue:@"\xe2\x8f\xa9"forKey:@"[指向右边的双三角]"];
      [dict setValue:@"\xe2\x8f\xaa"forKey:@"[向左的双三角]"];
      [dict setValue:@"\xe2\x8f\xab"forKey:@"[双三角]"];
      [dict setValue:@"\xe2\x8f\xac"forKey:@"[指向双三角]"];
      [dict setValue:@"\xf0\x9f\x94\xba"forKey:@"[向上红三角]"];
      [dict setValue:@"\xf0\x9f\x94\xbb"forKey:@"[向下红三角]"];
      [dict setValue:@"\xf0\x9f\x94\xbC"forKey:@"[向上指着红色小三角形]"];
      [dict setValue:@"\xf0\x9f\x94\xbD"forKey:@"[向下指的红色小三角形]"];
      [dict setValue:@"\xe2\xaD\x95"forKey:@"[大圈]"];
      [dict setValue:@"\xe2\x9d\x8c"forKey:@"[十字标记]"];
//      [dict setValue:@"\xe2\x9d\x8e"forKey:@"[负方CROSS MaRK]"];
      [dict setValue:@"\xe2\x9d\x97"forKey:@"[感叹号]"];
      [dict setValue:@"\xe2\x81\x89"forKey:@"[问号]"];
      [dict setValue:@"\xe2\x80\xbC"forKey:@"[双感叹号]"];
      [dict setValue:@"\xe2\x9d\x93"forKey:@"[黑色问号]"];
      [dict setValue:@"\xe2\x9d\x94"forKey:@"[白色问号]"];
      [dict setValue:@"\xe2\x9d\x95"forKey:@"[白色感叹号]"];
      [dict setValue:@"\xe3\x80\xb0"forKey:@"[波状]"];
      [dict setValue:@"\xe2\x9e\xb0"forKey:@"[卷发]"];
      [dict setValue:@"\xe2\x9e\xbf"forKey:@"[双花]"];
      [dict setValue:@"\xe2\x9d\xa4"forKey:@"[黑心]"];
      [dict setValue:@"\xf0\x9f\x92\x93"forKey:@"[跳动的心脏]"];
      [dict setValue:@"\xf0\x9f\x92\x94"forKey:@"[破碎的心]"];
      [dict setValue:@"\xf0\x9f\x92\x95"forKey:@"[两颗心]"];
      [dict setValue:@"\xf0\x9f\x92\x96"forKey:@"[光芒四射心]"];
      [dict setValue:@"\xf0\x9f\x92\x97"forKey:@"[成长心脏]"];
      [dict setValue:@"\xf0\x9f\x92\x98"forKey:@"[心与箭头]"];
      [dict setValue:@"\xf0\x9f\x92\x99"forKey:@"[蓝心]"];
      [dict setValue:@"\xf0\x9f\x92\x9a"forKey:@"[绿心]"];
      [dict setValue:@"\xf0\x9f\x92\x9b"forKey:@"[黄心]"];
      [dict setValue:@"\xf0\x9f\x92\x9c"forKey:@"[紫心]"];
      [dict setValue:@"\xf0\x9f\x92\x9d"forKey:@"[心与丝带]"];
      [dict setValue:@"\xf0\x9f\x92\x9e"forKey:@"[爱心]"];
      [dict setValue:@"\xf0\x9f\x92\x9f"forKey:@"[心形装饰]"];
      [dict setValue:@"\xe2\x99\xa5"forKey:@"[黑西装]"];
      [dict setValue:@"\xe2\x99\xa0"forKey:@"[黑桃]"];
      [dict setValue:@"\xe2\x99\xa6"forKey:@"[黑钻石西装]"];
      [dict setValue:@"\xe2\x99\xa3"forKey:@"[黑色梅花]"];
      [dict setValue:@"\xf0\x9f\x9a\xac"forKey:@"[吸烟]"];
      [dict setValue:@"\xf0\x9f\x9a\xaD"forKey:@"[禁止吸烟]"];
      [dict setValue:@"\xe2\x99\xbf"forKey:@"[轮椅]"];
      [dict setValue:@"\xf0\x9f\x9a\xa9"forKey:@"[三角棋]"];
      [dict setValue:@"\xe2\x9a\xa0"forKey:@"[警告标志]"];
      [dict setValue:@"\xe2\x9b\x94"forKey:@"[没有条目]"];
      [dict setValue:@"\xe2\x99\xbb"forKey:@"[回收标志]"];
      [dict setValue:@"\xf0\x9f\x9a\xb2"forKey:@"[自行车]"];
      [dict setValue:@"\xf0\x9f\x9a\xb6"forKey:@"[行人]"];
      [dict setValue:@"\xf0\x9f\x9a\xb9"forKey:@"[犯罪]"];
      [dict setValue:@"\xf0\x9f\x9a\xba"forKey:@"[妇女]"];
      [dict setValue:@"\xf0\x9f\x9b\x80"forKey:@"[卫浴]"];
      [dict setValue:@"\xf0\x9f\x9a\xbb"forKey:@"[厕所]"];
//      [dict setValue:@"\xf0\x9f\x9a\xbD"forKey:@"[TOILeT]"];
//      [dict setValue:@"\xf0\x9f\x9a\xbe"forKey:@"[水厕]"];
      [dict setValue:@"\xf0\x9f\x9a\xbC"forKey:@"[男孩子]"];
      [dict setValue:@"\xf0\x9f\x9a\xaa"forKey:@"[门]"];
      [dict setValue:@"\xf0\x9f\x9a\xab"forKey:@"[没有输入信号]"];
      [dict setValue:@"\xe2\x9c\x94"forKey:@"[重查]"];
//      [dict setValue:@"\xf0\x9f\x86\x91"forKey:@"[平方]"];
      [dict setValue:@"\xf0\x9f\x86\x92"forKey:@"[方形]"];
      [dict setValue:@"\xf0\x9f\x86\x93"forKey:@"[免费]"];
      [dict setValue:@"\xf0\x9f\x86\x94"forKey:@"[摆正]"];
      [dict setValue:@"\xf0\x9f\x86\x95"forKey:@"[NeW]"];
      [dict setValue:@"\xf0\x9f\x86\x96"forKey:@"[NG]"];
      [dict setValue:@"\xf0\x9f\x86\x97"forKey:@"[OK]"];
      [dict setValue:@"\xf0\x9f\x86\x98"forKey:@"[SOS]"];
      [dict setValue:@"\xf0\x9f\x86\x99"forKey:@"[感叹号]"];
//      [dict setValue:@"\xf0\x9f\x86\x9a"forKey:@"[平方VS]"];
//      [dict setValue:@"\xf0\x9f\x88\x81"forKey:@"[方形片假名KOKO]"];
//      [dict setValue:@"\xf0\x9f\x88\x82"forKey:@"[方形片假名Sa]"];
//      [dict setValue:@"\xf0\x9f\x88\xb2"forKey:@"[平方中日韩统一表意文字7981]"];
//      [dict setValue:@"\xf0\x9f\x88\xb3"forKey:@"[方形中日韩统一表意文字7a7a]"];
//      [dict setValue:@"\xf0\x9f\x88\xb4"forKey:@"[方形CJK统一表意文字-5408]"];
//      [dict setValue:@"\xf0\x9f\x88\xb5"forKey:@"[方形中日韩统一表意文字-6e80]"];
//      [dict setValue:@"\xf0\x9f\x88\xb6"forKey:@"[方形CJK统一表意文字-6709]"];
//      [dict setValue:@"\xf0\x9f\x88\x9a"forKey:@"[方形CJK统一表意文字-7121]"];
//      [dict setValue:@"\xf0\x9f\x88\xb7"forKey:@"[方形CJK统一表意文字-6708]"];
//      [dict setValue:@"\xf0\x9f\x88\xb8"forKey:@"[方形CJK统一表意文字-7533]"];
//      [dict setValue:@"\xf0\x9f\x88\xb9"forKey:@"[方形CJK统一表意文字-5272]"];
//      [dict setValue:@"\xf0\x9f\x88\xaf"forKey:@"[方形中日韩统一表意文字-6307]"];
//      [dict setValue:@"\xf0\x9f\x88\xba"forKey:@"[方形中日韩统一表意文字-55b6]"];
      [dict setValue:@"\xe3\x8a\x99"forKey:@"[秘密]"];
      [dict setValue:@"\xe3\x8a\x97"forKey:@"[恭喜]"];
      [dict setValue:@"\xf0\x9f\x89\x90"forKey:@"[优势]"];
      [dict setValue:@"\xf0\x9f\x89\x91"forKey:@"[接受]"];
      [dict setValue:@"\xe2\x9e\x95"forKey:@"[加号]"];
      [dict setValue:@"\xe2\x9e\x96"forKey:@"[减号]"];
      [dict setValue:@"\xe2\x9c\x96"forKey:@"[乘]"];
//      [dict setValue:@"\xe2\x9e\x97"forKey:@"[重科]"];
      [dict setValue:@"\xf0\x9f\x92\xa0"forKey:@"[一个点]"];
      [dict setValue:@"\xf0\x9f\x92\xa1"forKey:@"[电灯泡"];
      [dict setValue:@"\xf0\x9f\x92\xa2"forKey:@"[怒火]"];
      [dict setValue:@"\xf0\x9f\x92\xa3"forKey:@"[爆弹]"];
      [dict setValue:@"\xf0\x9f\x92\xa4"forKey:@"[睡]"];
      [dict setValue:@"\xf0\x9f\x92\xa5"forKey:@"[碰撞]"];
      [dict setValue:@"\xf0\x9f\x92\xa6"forKey:@"[溅]"];
      [dict setValue:@"\xf0\x9f\x92\xa7"forKey:@"[滴]"];
      [dict setValue:@"\xf0\x9f\x92\xa8"forKey:@"[破折号]"];
      [dict setValue:@"\xf0\x9f\x92\xa9"forKey:@"[桩公安条例]"];
      [dict setValue:@"\xf0\x9f\x92\xaa"forKey:@"[弯曲二头肌]"];
      [dict setValue:@"\xf0\x9f\x92\xab"forKey:@"[头晕]"];
      [dict setValue:@"\xf0\x9f\x92\xac"forKey:@"[气球]"];
      [dict setValue:@"\xe2\x9c\xa8"forKey:@"[火花]"];
//           [dict setValue:@"\xe2\x9c\xb4"forKey:@"[指出bLaCK STaR [八]"];
//           [dict setValue:@"\xe2\x9c\xb3"forKey:@"[八轮辐的aSTeRISK]"];
      [dict setValue:@"\xe2\x9a\xaa"forKey:@"[白圈]"];
      [dict setValue:@"\xe2\x9a\xab"forKey:@"[黑圈]"];
      [dict setValue:@"\xf0\x9f\x94\xb4"forKey:@"[红圈]"];
      [dict setValue:@"\xf0\x9f\x94\xb5"forKey:@"[蓝色圆]"];
      [dict setValue:@"\xf0\x9f\x94\xb2"forKey:@"[黑色方形按钮]"];
      [dict setValue:@"\xf0\x9f\x94\xb3"forKey:@"[白色的方形按钮]"];
      [dict setValue:@"\xe2\xaD\x90"forKey:@"[白色中星]"];
      [dict setValue:@"\xe2\xac\x9c"forKey:@"[白色大广场]"];
      [dict setValue:@"\xe2\xac\x9b"forKey:@"[黑色大型广场]"];
      [dict setValue:@"\xe2\x96\xab"forKey:@"[白色小广场]"];
      [dict setValue:@"\xe2\x96\xaa"forKey:@"[黑色小广场]"];
      [dict setValue:@"\xe2\x97\xbD"forKey:@"[白色中小广场]"];
      [dict setValue:@"\xe2\x97\xbe"forKey:@"[中黑色小广场]"];
      [dict setValue:@"\xe2\x97\xbb"forKey:@"[白色中广场]"];
      [dict setValue:@"\xe2\x97\xbC"forKey:@"[黑色中广场]"];
      [dict setValue:@"\xf0\x9f\x94\xb6"forKey:@"[橙色钻石]"];
      [dict setValue:@"\xf0\x9f\x94\xb7"forKey:@"[大蓝钻]"];
//      [dict setValue:@"\xf0\x9f\x94\xb8"forKey:@"[桔钻石]"];
      [dict setValue:@"\xf0\x9f\x94\xb9"forKey:@"[蓝钻石]"];
//      [dict setValue:@"\xe2\x9d\x87"forKey:@"[旌宇]"];
      [dict setValue:@"\xf0\x9f\x92\xae"forKey:@"[白色花]"];
//      [dict setValue:@"\xf0\x9f\x92\xaf"forKey:@"[百点符号]"];
      [dict setValue:@"\xe2\x86\xa9"forKey:@"[向左箭头]"];
      [dict setValue:@"\xe2\x86\xaa"forKey:@"[向右箭头]"];
      [dict setValue:@"\xf0\x9f\x94\x83"forKey:@"[顺时针向下]"];
      [dict setValue:@"\xf0\x9f\x94\x8a"forKey:@"[音箱]"];
      [dict setValue:@"\xf0\x9f\x94\x8b"forKey:@"[电池]"];
      [dict setValue:@"\xf0\x9f\x94\x8c"forKey:@"[电插头]"];
      [dict setValue:@"\xf0\x9f\x94\x8d"forKey:@"[指向左边的放大镜]"];
      [dict setValue:@"\xf0\x9f\x94\x8e"forKey:@"[指向右边的放大镜]"];
      [dict setValue:@"\xf0\x9f\x94\x92"forKey:@"[锁]"];
      [dict setValue:@"\xf0\x9f\x94\x93"forKey:@"[开锁]"];
      [dict setValue:@"\xf0\x9f\x94\x8f"forKey:@"[墨水钢笔]"];
      [dict setValue:@"\xf0\x9f\x94\x90"forKey:@"[关锁用钥匙]"];
      [dict setValue:@"\xf0\x9f\x94\x91"forKey:@"[钥匙]"];
      [dict setValue:@"\xf0\x9f\x94\x94"forKey:@"[钟]"];
      [dict setValue:@"\xe2\x98\x91"forKey:@"[投票箱]"];
      [dict setValue:@"\xf0\x9f\x94\x98"forKey:@"[单选按钮]"];
      [dict setValue:@"\xf0\x9f\x94\x96"forKey:@"[书签]"];
      [dict setValue:@"\xf0\x9f\x94\x97"forKey:@"[链接]"];
      [dict setValue:@"\xf0\x9f\x94\x99"forKey:@"[返回和向左箭头]"];
      [dict setValue:@"\xf0\x9f\x94\x9a"forKey:@"[结尾向左和箭头以上]"];
      [dict setValue:@"\xf0\x9f\x94\x9b"forKey:@"[感叹号和左右箭头]"];
      [dict setValue:@"\xf0\x9f\x94\x9c"forKey:@"[向右箭头​​]"];
      [dict setValue:@"\xf0\x9f\x94\x9d"forKey:@"[向上箭头]"];
      [dict setValue:@"\xe2\x80\x83" forKey:@"[空间]"];
      [dict setValue:@"\xe2\x80\x82"forKey:@"[空格]"];
//    [dict setValue:@"\xe2\x80\x85" forKey:@"[fOUR-PeR-eM空间]"];
//      [dict setValue:@"\xe2\x9c\x85"forKey:@"[白重查马克]"];
      [dict setValue:@"\xe2\x9c\x8b"forKey:@"[举手]"];
      [dict setValue:@"\xe2\x9c\x8c"forKey:@"[胜利]"];
      [dict setValue:@"\xf0\x9f\x91\x8a"forKey:@"[吝啬的]"];
      [dict setValue:@"\xf0\x9f\x91\x8d"forKey:@"[竖大拇指]"];
      [dict setValue:@"\xe2\x98\x9d"forKey:@"[指向白色]"];
      [dict setValue:@"\xf0\x9f\x91\x86" forKey:@"[指向反手]"];
      [dict setValue:@"\xf0\x9f\x91\x87" forKey:@"[向下的反手]"];
      [dict setValue:@"\xf0\x9f\x91\x88" forKey:@"[白左指反手]"];
      [dict setValue:@"\xf0\x9f\x91\x89" forKey:@"[向右的反手]"];
      [dict setValue:@"\xf0\x9f\x91\x8b"forKey:@"[挥舞着手势]"];
      [dict setValue:@"\xf0\x9f\x91\x8f"forKey:@"[拍双手]"];
      [dict setValue:@"\xf0\x9f\x91\x8c"forKey:@"[OK手势]"];
      [dict setValue:@"\xf0\x9f\x91\x8e"forKey:@"[朝下的手势]"];
      [dict setValue:@"\xf0\x9f\x91\x90"forKey:@"[张开双手]"];
       [dict setValue:@"\xf0\x9f\x98\x98" forKey:@"[飞吻红心]"];
    [dict setValue:@"\xf0\x9f\x98\x80" forKey:@"[圆眼睛微笑]"];
    [dict setValue:@"\xf0\x9f\x98\x97" forKey:@"[圆眼睛亲亲]"];
    [dict setValue:@"\xf0\x9f\x98\x99" forKey:@"[弯眼睛亲亲]"];
    [dict setValue:@"\xe2\x98\xba" forKey:@"[小嘴微笑]"];
    [dict setValue:@"\xf0\x9f\x98\x9b" forKey:@"[圆眼睛吐舌头]"];
    [dict setValue:@"\xf0\x9f\x98\x8e" forKey:@"[黑超小哥]"];
    [dict setValue:@"\xf0\x9f\x98\xb5" forKey:@"[眼睛X型展开嘴]"];
    [dict setValue:@"\xf0\x9f\x98\xb4" forKey:@"[亲，我要睡觉]"];
    [dict setValue:@"\xf0\x9f\x98\xae" forKey:@"[圆眼睛小嘴]"];
    [dict setValue:@"\xf0\x9f\x98\xac" forKey:@"[咬牙切齿，狠你]"];
    [dict setValue:@"\xf0\x9f\x98\x91" forKey:@"[亲，嘴巴一条线]"];
    [dict setValue:@"\xf0\x9f\x98\x9f" forKey:@"[我难过，我悲伤]"];
    [dict setValue:@"\xf0\x9f\x98\x90" forKey:@"[圆眼睛，嘴巴一条线]"];
    [dict setValue:@"\xf0\x9f\x98\xa6" forKey:@"[惊恐死我了]"];
    [dict setValue:@"\xf0\x9f\x98\x95" forKey:@"[不开心啦]"];
    [dict setValue:@"\xf0\x9f\x98\xa7" forKey:@"[有眉毛式惊恐]"];
    [dict setValue:@"\xf0\x9f\x98\xaf" forKey:@"[小嘴歪眉毛]"];
    [dict setValue:@"\xf0\x9f\x98\x88" forKey:@"[紫色头高兴]"];
    [dict setValue:@"\xf0\x9f\x98\xb6" forKey:@"[没有嘴巴呀]"];
    [dict setValue:@"\xf0\x9f\x98\x87" forKey:@"[天使]"];
    [dict setValue:@"\xe2\x9c\xa8" forKey:@"[三颗星]"];
    [dict setValue:@"\xe2\x9c\x8b" forKey:@"[给你掌心]"];
    [dict setValue:@"\xe2\x98\x9d" forKey:@"[竖食指]"];
    [dict setValue:@"\xe2\x9c\x8a" forKey:@"[掌心拳]"];
//    [dict setValue:@"\xe2\x9c\x8c" forKey:@"[YES]"];
    [dict setValue:@"\xf0\x9f\x91\xac" forKey:@"[牵手的哥们]"];
    [dict setValue:@"\xf0\x9f\x91\xad" forKey:@"[牵手的姐们]"];
    [dict setValue:@"\xf0\x9f\x99\x87" forKey:@"[小孩趴着]"];
    [dict setValue:@"\xf0\x9f\x91\xa5" forKey:@"[两个人的黑影]"];
    [dict setValue:@"\xe2\x9d\xa4" forKey:@"[大红心]"];
    [dict setValue:@"\xf0\x9f\x92\xad" forKey:@"[气团]"];
    [dict setValue:@"\xf0\x9f\x91\xbc" forKey:@"[天使在人间]"];
    
    return dict;
}
-(NSMutableDictionary*)ServerToXiTong{
    
    NSMutableDictionary *dict = [[[NSMutableDictionary alloc]init]autorelease];
    NSDictionary*  oldDict = [self XiTongToServer];
    for (NSString *key in [oldDict allKeys]) {
        NSString *newKey = [oldDict objectForKey:key];
        [dict setValue:key forKey:newKey];
    }
    return dict;
}



@end
